config/routes.rb
Kinohive::Application.routes.draw do

  resources :awarding_hivecoins

  resources :statistics

  resources :videos do
      collection do
   	 match 'search' => 'videos#search', :via => [:get, :post] , :as => :search
      end
  end

  get "home/index"

	match "/auth/:provider/callback" => "sessions#create"
	match "sessions/new" => "sessions#new"
	match '/signup', to: 'users#new'	
	match "/auth/failure" => "sessions#failure"
	match "/signout" => "sessions#destroy", :as => :signout

	match 'awarding_hivecoin', :controller => 'AwardingHivecoins', :action => 'awarding_hivecoin'

  devise_for :admins

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

	resources :identities
	
		resources :users do
		collection do
			put 'reset'
		end
	end 

	match '/user_profile', to:  'users#user_profile'
	match '/user_videos' => 'users#user_videos'
	match '/user_hivecoins' => 'users#user_hivecoins'
	match '/user_contributed_videos' => 'users#user_contributed_videos'
	match '/update_password' => 'users#update_password'
	match 'change_password' => 'users#change_password'
	match 'forgotpass' => 'users#forgotpass'
	match 'changepass' => 'users#changepass'
	match 'change' => 'users#change'

	

   root :to => 'videos#index'

end

app/models/awarding_hivecoin.rb
class AwardingHivecoin < ActiveRecord::Base
  attr_accessible :hivecoin, :user_id, :video_id
	belongs_to :video
	belongs_to :user
end

app/controllers/awarding_hivecoins_controller.rb
class AwardingHivecoinsController < ApplicationController
  # GET /awarding_hivecoins
  # GET /awarding_hivecoins.json
  def index
    @awarding_hivecoins = AwardingHivecoin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @awarding_hivecoins }
    end
  end

  # GET /awarding_hivecoins/1
  # GET /awarding_hivecoins/1.json
  def show
    @awarding_hivecoin = AwardingHivecoin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @awarding_hivecoin }
    end
  end

  # GET /awarding_hivecoins/new
  # GET /awarding_hivecoins/new.json
  def new
    @awarding_hivecoin = AwardingHivecoin.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @awarding_hivecoin }
    end
  end

  # GET /awarding_hivecoins/1/edit
  def edit
    @awarding_hivecoin = AwardingHivecoin.find(params[:id])
  end

  # POST /awarding_hivecoins
  # POST /awarding_hivecoins.json
  def create
    @awarding_hivecoin = AwardingHivecoin.new
	@awarding_hivecoin.hivecoin = params[:id]
	@awarding_hivecoin.video_id = @video.id
	@awarding_hivecoin.user_id = current_user.id

    respond_to do |format|
      if @awarding_hivecoin.save
        format.html { redirect_to @awarding_hivecoin, notice: 'Awarding hivecoin was successfully created.' }
        format.json { render json: @awarding_hivecoin, status: :created, location: @awarding_hivecoin }
      else
        format.html { render action: "new" }
        format.json { render json: @awarding_hivecoin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /awarding_hivecoins/1
  # PUT /awarding_hivecoins/1.json
  def update
    @awarding_hivecoin = AwardingHivecoin.find(params[:id])

    respond_to do |format|
      if @awarding_hivecoin.update_attributes(params[:awarding_hivecoin])
        format.html { redirect_to @awarding_hivecoin, notice: 'Awarding hivecoin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @awarding_hivecoin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /awarding_hivecoins/1
  # DELETE /awarding_hivecoins/1.json
  def destroy
    @awarding_hivecoin = AwardingHivecoin.find(params[:id])
    @awarding_hivecoin.destroy

    respond_to do |format|
      format.html { redirect_to awarding_hivecoins_url }
      format.json { head :no_content }
    end
  end
	
	def awarding_hivecoin
		@awarding_hivecoin = AwardingHivecoin.new
		@awarding_hivecoin.hivecoin = params[:id]
		@awarding_hivecoin.video_id = params[:videoid]
		@awarding_hivecoin.user_id = current_user.id


		#For video table
		@video = Video.find(params[:videoid])
		@video.update_attributes(:video_hivecoins => @video.video_hivecoins.to_i + params[:id].to_i)


		#For User table
		if !@video.user_id.blank?
			@awarded_video = User.find(@video.user_id)
			@awarded_video.update_attributes(:total_hivecoins => @video.video_hivecoins.to_i + @awarded_video.total_hivecoins.to_i)
		current_user.update_attributes(:total_hivecoins => current_user.total_hivecoins.to_i - params[:id].to_i)
		else
			@awarded_video = Admin.find(1)
			@awarded_video.update_attributes(:admin_hivecoins => @video.video_hivecoins.to_i + @awarded_video.admin_hivecoins.to_i)
		current_user.update_attributes(:total_hivecoins => current_user.total_hivecoins.to_i - params[:id].to_i)
		end
		@awarding_hivecoin.save
		render :partial => "hivecoin_count.html.erb"
	end

end

app/helpers/awarding_hivecoins_helper.rb
module AwardingHivecoinsHelper
end

app/views/awarding_hivecoins/_form.html.erb
<%= simple_form_for(@awarding_hivecoin) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :hivecoin %>
    <%= f.input :video_id %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/awarding_hivecoins/_hivecoin_count.html.erb
Video Hive Coins:  <strong> <%= @video.video_hivecoins.to_i %> </strong>

app/views/awarding_hivecoins/edit.html.erb
<h1>Editing awarding_hivecoin</h1>

<%= render 'form' %>

<%= link_to 'Show', @awarding_hivecoin %> |
<%= link_to 'Back', awarding_hivecoins_path %>

app/views/awarding_hivecoins/index.html.erb
<h1>Listing awarding_hivecoins</h1>

<table>
  <tr>
    <th>Hivecoin</th>
    <th>Video</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @awarding_hivecoins.each do |awarding_hivecoin| %>
  <tr>
    <td><%= awarding_hivecoin.hivecoin %></td>
    <td><%= awarding_hivecoin.video_id %></td>
    <td><%= awarding_hivecoin.user_id %></td>
    <td><%= link_to 'Show', awarding_hivecoin %></td>
    <td><%= link_to 'Edit', edit_awarding_hivecoin_path(awarding_hivecoin) %></td>
    <td><%= link_to 'Destroy', awarding_hivecoin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Awarding hivecoin', new_awarding_hivecoin_path %>

app/views/awarding_hivecoins/new.html.erb
<h1>New awarding_hivecoin</h1>

<%= render 'form' %>

<%= link_to 'Back', awarding_hivecoins_path %>

app/views/awarding_hivecoins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Hivecoin:</b>
  <%= @awarding_hivecoin.hivecoin %>
</p>

<p>
  <b>Video:</b>
  <%= @awarding_hivecoin.video_id %>
</p>

<p>
  <b>User:</b>
  <%= @awarding_hivecoin.user_id %>
</p>


<%= link_to 'Edit', edit_awarding_hivecoin_path(@awarding_hivecoin) %> |
<%= link_to 'Back', awarding_hivecoins_path %>