config/routes.rb
Kinohive::Application.routes.draw do

  resources :awarding_hivecoins

  resources :statistics

  resources :videos do
      collection do
   	 match 'search' => 'videos#search', :via => [:get, :post] , :as => :search
      end
  end

  get "home/index"

	match "/auth/:provider/callback" => "sessions#create"
	match "sessions/new" => "sessions#new"
	match '/signup', to: 'users#new'	
	match "/auth/failure" => "sessions#failure"
	match "/signout" => "sessions#destroy", :as => :signout

	match 'awarding_hivecoin', :controller => 'AwardingHivecoins', :action => 'awarding_hivecoin'

  devise_for :admins

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

	resources :identities
	
		resources :users do
		collection do
			put 'reset'
		end
	end 

	match '/user_profile', to:  'users#user_profile'
	match '/user_videos' => 'users#user_videos'
	match '/user_hivecoins' => 'users#user_hivecoins'
	match '/user_contributed_videos' => 'users#user_contributed_videos'
	match '/update_password' => 'users#update_password'
	match 'change_password' => 'users#change_password'
	match 'forgotpass' => 'users#forgotpass'
	match 'changepass' => 'users#changepass'
	match 'change' => 'users#change'

	

   root :to => 'videos#index'

end

app/models/statistic.rb
class Statistic < ActiveRecord::Base
  attr_accessible :concept, :content, :editing, :shots, :user_id, :video_id

  belongs_to :user
  belongs_to :video
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  # GET /statistics
  # GET /statistics.json
  def index
    @statistics = Statistic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statistics }
    end
  end

  # GET /statistics/1
  # GET /statistics/1.json
  def show
    @statistic = Statistic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @statistic }
    end
  end

  # GET /statistics/new
  # GET /statistics/new.json
  def new
    @statistic = Statistic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @statistic }
    end
  end

  # GET /statistics/1/edit
  def edit
    @statistic = Statistic.find(params[:id])
  end

  # POST /statistics
  # POST /statistics.json
  def create
	@user_critic_hivecoin = (Statistic.where(:user_id => params[:statistic][:user_id]).count+1) % 3
	@user = User.find(params[:statistic][:user_id])
    @statistic = Statistic.new(params[:statistic])
    respond_to do |format|
      if @statistic.save
		if @user_critic_hivecoin == 0
			@user.update_attributes(:total_hivecoins => @user.total_hivecoins + 1)
		end 
        format.html { redirect_to request.referer, notice: 'Statistic was successfully created.' }
        format.json { render json: @statistic, status: :created, location: @statistic }
      else
        format.html { render action: "new" }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statistics/1
  # PUT /statistics/1.json
  def update
    @statistic = Statistic.find(params[:id])

    respond_to do |format|
      if @statistic.update_attributes(params[:statistic])
        format.html { redirect_to @statistic, notice: 'Statistic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statistics/1
  # DELETE /statistics/1.json
  def destroy
    @statistic = Statistic.find(params[:id])
    @statistic.destroy

    respond_to do |format|
      format.html { redirect_to statistics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/statistics/_form.html.erb
<!-- :url => {:action => "create", :controller => 'statistics'}, :remote => true -->
<style>
.form-horizontal .control-label
{
	width:90px;
	text-align:left;
}

.form-horizontal .controls
{

	margin-left:0px;
		
}
</style>
<h2> Getting Statistics </h2>
<%= simple_form_for( @statistic, :html=>{class: 'form-horizontal' })  do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

 <%= f.input :content, :collection => ["Original","Smart","Unexpected","It's Ok", "Boring", "Pain Full"], :as => :radio_buttons, :checked =>"#{@statistic.content}",:item_wrapper_class => 'inline' %> 
 <%= f.input :editing, :collection => ["Seanless","Choppy"], :as => :radio_buttons, :checked =>"#{@statistic.content}",:item_wrapper_class => 'inline' %> 
	<%= f.input :shots, :collection => ["Beautiful","Need Work"], :as => :radio_buttons, :checked =>"#{@statistic.content}",:item_wrapper_class => 'inline' ,:label => 'Shots' %> 
	
    <%= f.input :concept, :collection => ["Great Idea!","Interesting","I Dont get it","Cliche"], :as => :radio_buttons, :checked =>"#{@statistic.content}",:item_wrapper_class => 'inline' ,:label => 'Concept' %>
    <%= f.input :video_id, :as => :hidden, :input_html => { :value => @video.id }%>
    <%= f.input :user_id, :as => :hidden, :input_html => {:value => current_user.id} %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :value => 'Submit' %>
  </div>
<% end %>

app/views/statistics/edit.html.erb
<h1>Editing statistic</h1>

<%= render 'form' %>

<%= link_to 'Show', @statistic %> |
<%= link_to 'Back', statistics_path %>

app/views/statistics/index.html.erb
<h1>Listing statistics</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Editing</th>
    <th>Shots</th>
    <th>Concept</th>
    <th>Video</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @statistics.each do |statistic| %>
  <tr>
    <td><%= statistic.content %></td>
    <td><%= statistic.editing %></td>
    <td><%= statistic.shots %></td>
    <td><%= statistic.concept %></td>
    <td><%= statistic.video_id %></td>
    <td><%= statistic.user_id %></td>
    <td><%= link_to 'Show', statistic %></td>
    <td><%= link_to 'Edit', edit_statistic_path(statistic) %></td>
    <td><%= link_to 'Destroy', statistic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Statistic', new_statistic_path %>

app/views/statistics/new.html.erb
<h1>New statistic</h1>

<%= render 'form' %>

<%= link_to 'Back', statistics_path %>

app/views/statistics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @statistic.content %>
</p>

<p>
  <b>Editing:</b>
  <%= @statistic.editing %>
</p>

<p>
  <b>Shots:</b>
  <%= @statistic.shots %>
</p>

<p>
  <b>Concept:</b>
  <%= @statistic.concept %>
</p>

<p>
  <b>Video:</b>
  <%= @statistic.video_id %>
</p>

<p>
  <b>User:</b>
  <%= @statistic.user_id %>
</p>


<%= link_to 'Edit', edit_statistic_path(@statistic) %> |
<%= link_to 'Back', statistics_path %>