config/routes.rb
Kinohive::Application.routes.draw do

  resources :awarding_hivecoins

  resources :statistics

  resources :videos do
      collection do
   	 match 'search' => 'videos#search', :via => [:get, :post] , :as => :search
      end
  end

  get "home/index"

	match "/auth/:provider/callback" => "sessions#create"
	match "sessions/new" => "sessions#new"
	match '/signup', to: 'users#new'	
	match "/auth/failure" => "sessions#failure"
	match "/signout" => "sessions#destroy", :as => :signout

	match 'awarding_hivecoin', :controller => 'AwardingHivecoins', :action => 'awarding_hivecoin'

  devise_for :admins

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

	resources :identities
	
		resources :users do
		collection do
			put 'reset'
		end
	end 

	match '/user_profile', to:  'users#user_profile'
	match '/user_videos' => 'users#user_videos'
	match '/user_hivecoins' => 'users#user_hivecoins'
	match '/user_contributed_videos' => 'users#user_contributed_videos'
	match '/update_password' => 'users#update_password'
	match 'change_password' => 'users#change_password'
	match 'forgotpass' => 'users#forgotpass'
	match 'changepass' => 'users#changepass'
	match 'change' => 'users#change'

	

   root :to => 'videos#index'

end

app/models/video.rb
class Video < ActiveRecord::Base
	require 'uri'
	require 'file_size_validator'
  attr_accessible :user_id, :video_hivecoins, :video_pic, :video_title, :video_url, :video_pic_cache, :remove_video_pic
  mount_uploader :video_pic, VideopicUploader
  belongs_to :user
  has_many :statistics, dependent: :destroy
  has_many :awarding_hivecoins, dependent: :destroy
  validates :video_pic,  
    :file_size => { 
      :maximum => 0.003.megabytes.to_i 
    } 
  
    def embed(width = "300" , height = "182")
    #iframe code should be the same for vimeo and youtube
    embed_code = "<iframe width='#{width}' height='#{height}' src='#{url}' frameborder='0' allowfullscreen></iframe>"
  end

  private

  def url
    url = nil
    case base_uri
      when "www.youtube.com" , "youtu.be"
        url = "http://www.youtube.com/embed/"+ video_id + '?' + "rel=0"
      when "www.vimeo.com" , "vimeo.com"
        url = "http://player.vimeo.com/video/" + video_id
    end

    url    
  end

  def video_id
    video_id = nil
    case base_uri
      when "www.youtube.com"
        video_id = @uri.query.split('=')[1].slice(0, 11)
      when "youtu.be"
        video_id = @uri.path.delete('/')
      when "www.vimeo.com" , "vimeo.com"
        video_id = @uri.path.delete('/')
      end
    video_id
  end

  def base_uri
    @uri ||= parse_it

    @uri.host
  end
  
  def parse_it
      @uri = URI.parse( code )
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  # GET /videos
  # GET /videos.json
  before_filter :authorize, :except => [:index, :show, :search]
  before_filter :record_visit, :only => [:index, :show] 
  before_filter :count_views
  
  def index
  
    @api = Embedly::API.new(:key => 'd3f1d48b58d94330b206f80a2ab72181')
    @q = Video.search(params[:q])
    @videos = @q.result.order("video_hivecoins DESC")


#    @videos = Video.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @videos }
    end
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
      @api = Embedly::API.new(:key => 'd3f1d48b58d94330b206f80a2ab72181')
    @video = Video.find(params[:id])
    if @video.user_id==nil
	
	@videos=Video.where(:user_id=>nil)
	
   else
   
   	@videos=Video.where(:user_id=>@video.user_id)
   end
    
	@statistic = Statistic.new
		if current_user
			@taken_critic = Statistic.find_by_user_id_and_video_id(current_user.id,@video.id)
		end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/new
  # GET /videos/new.json
  def new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video }
    end
  end

  # GET /videos/1/edit
  def edit
    @video = Video.find(params[:id])
  end

  # POST /videos
  # POST /videos.json
  def create
  	@api = Embedly::API.new(:key => 'd3f1d48b58d94330b206f80a2ab72181')
    @video = Video.new(params[:video])
    @video.user_id=current_user.id
    
    respond_to do |format|
      if @video.save
        format.html { redirect_to videos_path, notice: 'Video was successfully Uploaded.' }
        format.json { render json: @video, status: :created, location: @video }
      else
        format.html { render action: "new" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /videos/1
  # PUT /videos/1.json
  def update
    @video = Video.find(params[:id])

    respond_to do |format|
      if @video.update_attributes(params[:video])
        format.html { redirect_to videos_path, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end
  
  def search
  
    @api = Embedly::API.new(:key => 'd3f1d48b58d94330b206f80a2ab72181')
    @q = Video.search(params[:q])
    @videos = @q.result.order("video_hivecoins DESC")
    
  end


  def count_views
	@views = Visit.where(page: request.fullpath).count
#	@non_users = Visit.where(user_id: nil).count
#  	@video_views = Visit.where('page =?', request.fullpath).select('distinct ip_address').count
#		@total_views = 0;
#		@video_views.values.each do |views|
#			@total_views += views.to_i
#		end
#	@total_views += @non_users	
  end
  
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= simple_form_for( @video, :html=>{:multipart => true, class: 'form-horizontal' })  do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :video_title, :label => "Title" %>
    
    <%= f.input :video_url %>

    <%= f.input :video_pic, :label=>"Upload Video Image" %>

  </div>

  <div class="form-actions">
    <% if controller.action_name == 'new' %>
    <%= f.submit "Upload Video", class: 'btn btn-primary' %>
   <% else %> 
   <%= f.submit "Update Video", class: 'btn btn-primary' %>
   <% end %> 
  </div>
<% end %>

app/views/videos/_hivecoin_count.html.erb
Video Hive Coins:  <strong> <%= @video.video_hivecoins.to_i %> </strong>

app/views/videos/_search_form.html.erb
<html>
<head >
<style>
.searchbox
{
	border-radius:15px !important;
	width:200px !important;
	text-align:center;
	position:absolute;
	top: 10px;
	right: 50px;
	
}
.search_button {
	position: absolute;
	top:14px;	
	right:60px;
	width:20px;
	height:20px;
}

</style>
<script>

$(function() {

    var availableTags = <%= Video.all.map(&:video_title).to_json.html_safe %>;

    $( ".searchbox" ).autocomplete({
	
	source: availableTags

    });

});
</script>

  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
  
</head>
<body>
 

  
<div class="offset1">

 <%= search_form_for @q,:url => search_videos_path,:html => {class: 'form-horizontal '}  do |f| %>
<div class="control-group" >
     
<%= f.text_field :video_title_cont, placeholder: 'Search Videos', :class=>"searchbox"  %> 
  </div>
<% end %>
</div>
<%=image_tag('search.ico', class:'search_button')%>
</body>
</html>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

app/views/videos/index.html.erb
<html>
<style>

</style>
<body>

<div class='row'>
	<div class='span12'>
			<%= render :partial => "search_form.html.erb", locals: {q: @q} %>
					<!-- Displaying Most Hivecoin Videos -->
			<div>
				<% if !@videos.blank?%>
					<h4> Most Hivecoins Videos </h4>
					<table>
						<tr>
					<%@videos.each do |video|%>
						<td>
					  	<% if !video.video_pic.blank? %>
			<%= link_to image_tag(video.video_pic_url, class: "video_pic"), video_path(video), title: "#{video.video_title}" %> 
						<% else %>
			<%= link_to image_tag('video.png', class: "video_pic"), video_path(video), title: "#{video.video_title}" %>
						<% end %>
						</td>
					<%end%>
						</tr>
					</table>
				<%else%>
				<table> <tr> <th> No Videos to Display </th> </tr> </table>
				<%end%>
			</div>

			<!-- Displaying Geographical Videos -->
			<div>
				<% if current_user %>
					<h4> Geographical Videos </h4>
					<table>
						<tr>
							<%@videos.each do |video|%>
						<% if !video.user_id.blank?%>
							<% if current_user.city === User.find(video.user_id).city %>
								<td>
								<% if !video.video_pic.blank? %>
									<%= link_to image_tag(video.video_pic_url, :class=>"video_pic"), video_path(video), title: "#{video.video_title}" %> 
								<% else %>
									<%= link_to image_tag('video.png', class: 'video_pic'), video_path(video), title: "#{video.video_title}" %>
								<% end %>
								</td>
							<% end %>
						<% end %>
						
				<% end %> </tr>
						</table>
				<% end %>
			</div>

			<!-- Displaying No of Viewers of this site -->
			<div style="position:absolute;bottom:10px;right:10px;">
				Visited Members: <%= @views %>
			</div>
	</div>
</div>
</body>
</html>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

app/views/videos/search.html.erb
<html>

<body>

<div class='row'>
	<div class='span12'>
			<%= render :partial => "search_form.html.erb", locals: {q: @q} %>
					<!-- Displaying Most Hivecoin Videos -->
			<div>
				<% if !@videos.blank?%>
					<h4> Most Hivecoins Videos </h4>
					<table>
						<tr>
					<%@videos.each do |video|%>
						<td>
					  	<% if !video.video_pic.blank? %>
			<%= link_to image_tag(video.video_pic_url, :class=>"video_pic"), video_path(video), title: "#{video.video_title}" %> 
						<% else %>
			<%= link_to image_tag('video.png', class: 'video_pic'), video_path(video), title: "#{video.video_title}" %>
						<% end %>
						</td>
					<%end%>
						</tr>
					</table>
				<%else%>
				<table> <tr> <th> No Videos to Display </th> </tr> </table>
				<%end%>
			</div>
	</div>
</div>
</body>
</html>

app/views/videos/show.html.erb
<html>

<style>
.description
{

	padding-left:5px !important;
	padding-top:30px;
	padding-bottom:50px;
	
	
}
</style>
<script>
	$(function() { 
		$('#hivecoins_awarding').change(function() { 
			var awarded_amount = $(this).val();
			var video_id = <%= @video.id %>
			//alert(awarded_amount)
			//alert(video_id)
			$.ajax({
				url:'/awarding_hivecoin',
				data: { id:awarded_amount, 
						videoid: video_id},
				dataType: 'html',
				success: function(data) {
					$('.result').html(data);
				},
				error: function(data) {
						alert('error Occurred')
				}
			});
		});
		
	});
</script>

<body>

<div class="container">

<div style="float:left"><!-- left div-->
<div> 
	
	<% vurl = @api.oembed(
       :url => @video.video_url,
       :maxwidth => 600
       )  %>
		<span class="embed-item"> <%= raw(vurl[0].html) %>
          </span> 
</div>
<br/>
<div > <!-- Critics Div Starting-->

<%#= render :partial => 'hivecoin_count'%>
<div style=" margin-left:56%">

<div class='result' style='display:inline'>
 &nbsp;&nbsp;
	<% if current_user %>
	<% if @video.user_id != current_user.id %>
		<%if user_awarded_hivecoins?(current_user.id,@video.id).nil? %>
<select id='hivecoins_awarding' class='awarding_hivecoins'>
	<% if current_user.total_hivecoins >= 3 %>
		<option value='0'> 0 </option>
		<option value='1'> 1 </option>
		<option value='2'> 2 </option>
		<option value='3'> 3 </option>		
	<% elsif current_user.total_hivecoins ==2 %>
		<option value='0'> 0 </option>
		<option value='1'> 1 </option>
		<option value ='2'> 2 </option>
	<% elsif current_user.total_hivecoins ==1 %>
		<option value='0'> 0 </option>
		<option value='1'> 1 </option>
	<% end %>	
		<% end %>
</select>
	<% end %>
<% end %>
Video Hive Coins:  <strong> <%= @video.video_hivecoins.to_i %> </strong>
</div>
<span>  Views <%= @video_views %> </span>
</div> 

<% if current_user || current_admin  %>
	<% if current_user %>
	<% if @taken_critic.nil? && !own_videos?(current_user.id, @video.id)%>
		<%= render :partial => 'statistics/form' %>
	<% else %>
		<strong> You have already gave the critic to this video </strong>
	<% end %>
	<% end %>
<% end %>

</div> <!-- Critics Div Ending-->
	
</div><!-- left div Ending-->

<!-- Related Videos -->

<div style="float:right;width:300px;display:none;"> <!-- Right Div-->

<% @videos.each do |video| %>
		
<div>
		<% if !video.video_url.blank?  %> 
		<% vurl = @api.oembed(
       :url => video.video_url,
       :maxwidth => 150
       )  %>
<p style="float:left;padding-right:10px">

<span class="embed-item"><a  href="<%= video_path(video) %> "> <%= image_tag(vurl[0].thumbnail_url ,:width=>150) %> </a></span> 

</p>

<p class="description">

<span ><b>Title </b> : <%=video.video_title%></span></br>
<span ><b>Hive Coins </b> : <%= video.video_hivecoins.to_i %> </spn>


</p>

</div>	


      <% end %>

<%end%>
</div> <!-- Right Div End-->

<!-- Video Owner Details -->
<div class="span4">
		<% if !@video.user_id.blank? %>
			<h4> Video Owner Details </h4>
				<% @video_owner = User.find(@video.user_id)  %>
				<span ><b>Name </b> : <%= @video_owner.name.camelize %> </span></br>
				<span ><b>Email </b> : <%= @video_owner.email %> </span> <br />
				<span ><b>City </b> : <%= @video_owner.city.camelize %> </span></br>
				<span ><b>State </b> : <%= @video_owner.state.camelize %> </span>
		<% else %>
			<h4> Video Owner Details </h4>
				<% @video_owner = Admin.find(1)  %>
				<span ><b>Name </b> : <%= @video_owner.name.camelize %> </span></br>
				<span ><b>Email </b> : <%= @video_owner.email %> </span> <br />
				<span ><b>City </b> : <%= @video_owner.city.camelize %> </span></br>
				<span ><b>State </b> : <%= @video_owner.state.camelize %> </span>
		<% end %>	
</div>
</div>

</body>
</html>

<style>
	.awarding_hivecoins {
		width: 50px;
	}
</style>