config/routes.rb
Kinohive::Application.routes.draw do

  resources :awarding_hivecoins

  resources :statistics

  resources :videos do
      collection do
   	 match 'search' => 'videos#search', :via => [:get, :post] , :as => :search
      end
  end

  get "home/index"

	match "/auth/:provider/callback" => "sessions#create"
	match "sessions/new" => "sessions#new"
	match '/signup', to: 'users#new'	
	match "/auth/failure" => "sessions#failure"
	match "/signout" => "sessions#destroy", :as => :signout

	match 'awarding_hivecoin', :controller => 'AwardingHivecoins', :action => 'awarding_hivecoin'

  devise_for :admins

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

	resources :identities
	
		resources :users do
		collection do
			put 'reset'
		end
	end 

	match '/user_profile', to:  'users#user_profile'
	match '/user_videos' => 'users#user_videos'
	match '/user_hivecoins' => 'users#user_hivecoins'
	match '/user_contributed_videos' => 'users#user_contributed_videos'
	match '/update_password' => 'users#update_password'
	match 'change_password' => 'users#change_password'
	match 'forgotpass' => 'users#forgotpass'
	match 'changepass' => 'users#changepass'
	match 'change' => 'users#change'

	

   root :to => 'videos#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KinoHIve</title>
  
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>
<style>
.nav li{margin-top:12px;}
.nav img{margin-top:-17px;}

</style>
<body>

  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <ul class="nav">

          <li><%= link_to 'Home', root_path %></li>

		<% if current_user %>

			<li>	<%= link_to current_user.name, '/user_profile'%> </li>
		<% end %>

 		<% if current_user || current_admin %>

			<li><%= link_to 'Upload',  new_video_path %></li>
					
		<%end%>
		
		<% if current_user  %>
			<li><%= link_to 'Signout', signout_path, :id => 'sign_out' %></li>
		<%elsif current_admin%>

<li><a href="/admins/sign_out" data-method="delete" rel="nofollow"><span class="label label-important">Log out</span></a></li>
		<% else %>
		
			<li><%= link_to 'Signin','/sessions/new', id: 'sign_in' %></li>
		<% end %>

		         
        </ul>
        
            </div>
    </div>
  </div>  
  <div class="container">
    
    <div id="notifications">
    <% [:error, :notice, :alert].each do |type| %>
      <% if flash[type] %>
        <%= content_tag :div, class: "alert #{alert_class(type)}" do %>
        <a class="close" data-dismiss="alert">x</a>
        <%= flash[type] %>
        <% end %>
      <% end %>
    <% end %>
    </div>

    <div class="row">
      <div class="span12">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>